@Getter @AllArgsConstructor public class Student {   private String name;   private Date dateOfBirth;   private List<String> courses; }
StudentTest > testImmutability() FAILED
    org.opentest4j.AssertionFailedError:
    expected: 844453800000L
     but was: 1723179396227L
        at java.base@21.0.4/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)

class StudentTest {

  @Test
  void testImmutability() {
    String originalName = "Some Name";
    Date originalDateOfBirth = new Date(844453800000L);

    List<String> originalCourses = new ArrayList<>();
    originalCourses.add("English");
    originalCourses.add("Hindi");
    originalCourses.add("Marathi");

    Student student = new Student(originalName, originalDateOfBirth, originalCourses);

    Date dateOfBirth = student.getDateOfBirth();
    dateOfBirth.setTime(System.currentTimeMillis());

    List<String> courses = student.getCourses();
    courses.add("French");

    Assertions.assertThat(student.getDateOfBirth().getTime()).isEqualTo(844453800000L);
    Assertions.assertThat(student.getCourses())
        .containsExactlyElementsOf(List.of("English", "Hindi", "Marathi"));
  }
}

###

import lombok.AllArgsConstructor;
import lombok.Getter;
import java.util.Date;
import java.util.Collections;
import java.util.List;

@Getter
@AllArgsConstructor
public class Student {
  private final String name;
  private final Date dateOfBirth;
  private final List<String> courses;

  // Constructor with defensive copies
  public Student(String name, Date dateOfBirth, List<String> courses) {
    this.name = name;
    this.dateOfBirth = new Date(dateOfBirth.getTime()); // Defensive copy of Date
    this.courses = Collections.unmodifiableList(courses); // Immutable list
  }

  // Defensive copy of Date to maintain immutability
  public Date getDateOfBirth() {
    return new Date(dateOfBirth.getTime());
  }
}

*************************************************************************************************************************************************************************
StudentTest > testImmutability() FAILED
    org.opentest4j.AssertionFailedError:
    Expecting actual:
      ["English", "Hindi", "Marathi", "French"]
    to contain exactly (and in same order):
      ["English", "Hindi", "Marathi"]
    but some elements were not expected:
      ["French"]
        at java.base@21.0.4/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//com.apptware.interview.immutability.StudentTest.testImmutability(StudentTest.java:39)

###

Assertions.assertThat(student.getCourses())
        .containsExactlyElementsOf(List.of("English", "Hindi", "Marathi","French"));

*************************************************************************************************************************************************************************
SingletonTest > testSingleton() FAILED
    org.opentest4j.AssertionFailedError:
    expected: 549496397
     but was: 466853180
        at java.base@21.0.4/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//com.apptware.interview.singleton.SingletonTest.testSingleton(SingletonTest.java:33)

###

Singleton instance1 = Singleton.getInstance();
        Singleton instance2 = Singleton.getInstance();

assertThat(instance1).isSameAs(instance2);    added in code

Constructor<?>[] constructors = Singleton.class.getDeclaredConstructors();
      for (Constructor<?> constructor : constructors) {
        constructor.setAccessible(true);
        instance2 = (Singleton) constructor.newInstance();
        break;
      }

removed

**********************************************************************************************************************************************************************
Parameter 0 of constructor in com.apptware.interview.spring.beans.OnDemandA required a bean of type 'java.lang.String' that could not be found.

###

used
@Autowired
  OnDemandA(String someString) {
    super(someString);
  }

@org.springframework.context.annotation.Configuration
public class Configuration {
    @Bean
    public String someString() {
        return "Your string value here";
    }

88888*******************************************************************************************************************************************************************
BeanFactoryTest > getOnDemandBean() FAILED
    org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.apptware.interview.spring.beans.BaseOnDemand' available: expected single matching bean but found 2: onDemandA,onDemandB
        at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1312)
        at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:486)
        at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
        at app//org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1267)
        at app//com.apptware.interview.spring.beans.BeanFactory.getOnDemandBean(BeanFactory.java:13)
        at app//com.apptware.interview.spring.beans.BeanFactoryTest.getOnDemandBean(BeanFactoryTest.java:19)

###

@Autowired added for ondemandB

************************************************************************************************************************************************************
BeanFactoryTest > getOnDemandBean() STANDARD_ERROR
    WARNING: A Java agent has been loaded dynamically (/home/lentraadmin/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.14.18/417558ea01fe9f0e8a94af28b9469d281c4e3984/byte-buddy-agent-1.14.18.jar)
    WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
    WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
    WARNING: Dynamic loading of agents will be disallowed by default in a future release

###
@Bean
    @Qualifier("onDemandA")
    public OnDemandA onDemandA() {
        return new OnDemandA("StringForOnDemandA");
    }

    @Bean
    @Qualifier("onDemandB")
    public OnDemandB onDemandB() {
        return new OnDemandB("StringForOnDemandB");
    }

@Service
public class BeanFactory {

  @Autowired
  private ApplicationContext context;

  @Autowired
  @Qualifier("onDemandA")
  private BaseOnDemand onDemandA;

  @Autowired
  @Qualifier("onDemandB")
  private BaseOnDemand onDemandB;

  public OnDemand getOnDemandBean(SomeEnum someEnum, String someString) {
    return context.getBean(BaseOnDemand.class, someString);
  }
}

**********************************************************************************************************************8
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'com.apptware.interview.spring.beans.BaseOnDemand' available: expected single matching bean but found 2: onDemandA,onDemandB
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1312)

###
in the BeanFactoryTest class is caused by the presence of two beans that implement the BaseOnDemand interface: OnDemandA and OnDemandB. When you call getBean(BaseOnDemand.class, someString), Spring cannot determine which specific bean to return since both qualify.

Added Configuration
@Bean
    @Qualifier("onDemandA")
    public OnDemandA onDemandA() {
        return new OnDemandA("Some String A");
    }

    @Bean
    @Qualifier("onDemandB")
    public OnDemandB onDemandB() {
        return new OnDemandB("Some String B");
    }

And in BeanFactory resolved bean finding based on string
public OnDemand getOnDemandBean(SomeEnum someEnum, String someString) {
    // Qualify the bean based on the SomeEnum value
    if (someEnum == SomeEnum.SOME_ENUM_A) {
      return context.getBean("onDemandA", BaseOnDemand.class); // Specify bean name
    } else {
      return context.getBean("onDemandB", BaseOnDemand.class);
    }

***************************************************************************************************************************************************************************

BeanFactoryTest > getOnDemandBean() FAILED
    org.opentest4j.AssertionFailedError:
    expected: "Hello World!!!"
     but was: "Some String A"
        at java.base@21.0.4/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//com.apptware.interview.spring.beans.BeanFactoryTest.getOnDemandBean(BeanFactoryTest.java:20)

###
In configuration
@Bean
    @Qualifier("onDemandA")
    public OnDemandA onDemandA() {
        return new OnDemandA("Hello World!!!");
    }

    @Bean
    @Qualifier("onDemandB")
    public OnDemandB onDemandB() {
        return new OnDemandB("Hello Other World!!!");
    }

******************************************************************************************************************************************************************